version: '3.8'
services:
  helloservice:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
#      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
#    volumes:
#      - ./:/app
#    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
   logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"
   container_name: my-demo-app-container-prod
   command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "springboot-docker.jar"]

#  mysqlserver:
#    image: mysql:8.0.23
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=petclinic
#      - MYSQL_PASSWORD=petclinic
#      - MYSQL_DATABASE=petclinic
#    volumes:
#      - mysql_data:/var/lib/mysqcommand: ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "springboot-docker.jar"]l
#      - mysql_config:/etc/mysql/conf.d
# volumes:
#  mysql_data:
#  mysql_config: